// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIfOWEZ3OA_KR3Wb34QMC6cCPH4J3a6HY',
    appId: '1:885245504058:web:5d132156a092c4c95c6303',
    messagingSenderId: '885245504058',
    projectId: 'user-authentication-demo-a43d9',
    authDomain: 'user-authentication-demo-a43d9.firebaseapp.com',
    storageBucket: 'user-authentication-demo-a43d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmb1L05Pnls9HDuf4fVKbkPTHFD4cKYpQ',
    appId: '1:885245504058:android:8ca6cd597c41e54b5c6303',
    messagingSenderId: '885245504058',
    projectId: 'user-authentication-demo-a43d9',
    storageBucket: 'user-authentication-demo-a43d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuVmldWF8oXXfrRcHTRFe8POMAcf2mecM',
    appId: '1:885245504058:ios:485a7795133ec8a25c6303',
    messagingSenderId: '885245504058',
    projectId: 'user-authentication-demo-a43d9',
    storageBucket: 'user-authentication-demo-a43d9.firebasestorage.app',
    iosBundleId: 'com.innovatedy.userAuthenticationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuVmldWF8oXXfrRcHTRFe8POMAcf2mecM',
    appId: '1:885245504058:ios:485a7795133ec8a25c6303',
    messagingSenderId: '885245504058',
    projectId: 'user-authentication-demo-a43d9',
    storageBucket: 'user-authentication-demo-a43d9.firebasestorage.app',
    iosBundleId: 'com.innovatedy.userAuthenticationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIfOWEZ3OA_KR3Wb34QMC6cCPH4J3a6HY',
    appId: '1:885245504058:web:50eab9c322cfb4695c6303',
    messagingSenderId: '885245504058',
    projectId: 'user-authentication-demo-a43d9',
    authDomain: 'user-authentication-demo-a43d9.firebaseapp.com',
    storageBucket: 'user-authentication-demo-a43d9.firebasestorage.app',
  );
}
